In [13]:
import torch

In [20]:
ten = torch.tensor([
    [1,2,3,4],
    [3,4,5,6],
    [3,8,6,1]
], dtype=torch.float32)
print(ten)

tensor([[1., 2., 3., 4.],
        [3., 4., 5., 6.],
        [3., 8., 6., 1.]])


In [22]:
ten.size()

torch.Size([3, 4])

In [23]:
ten.shape

torch.Size([3, 4])

In [24]:
len(ten.shape)

2

In [35]:
torch.tensor(ten.shape).prod()

tensor(12)

In [37]:
ten.numel()

12

In [42]:
ten.reshape(2,6)

tensor([[1., 2., 3., 4., 3., 4.],
        [5., 6., 3., 8., 6., 1.]])

In [50]:
print(ten.reshape(1,12).squeeze())
print(ten.reshape(1,12).squeeze().shape)

tensor([1., 2., 3., 4., 3., 4., 5., 6., 3., 8., 6., 1.])
torch.Size([12])


In [55]:
print(ten.reshape(2,6).unsqueeze(dim=0))
print(ten.reshape(2,6).unsqueeze(dim=0).shape)

tensor([[[1., 2., 3., 4., 3., 4.],
         [5., 6., 3., 8., 6., 1.]]])
torch.Size([1, 2, 6])


In [61]:
ten2 = torch.randn_like(ten)
print(ten2)

tensor([[-1.0556,  2.0221,  0.9385, -1.1676],
        [-0.0429, -1.5460,  0.5390, -0.1666],
        [-0.2079,  0.5444, -1.1509, -0.4112]])


In [66]:
#mm
mul = torch.mm(ten,ten2.view(4,3))
print(mul)

tensor([[  0.4038,  -3.1672,  -4.4221],
        [ -1.8757,  -1.8439,  -6.8754],
        [ -8.7291,   3.5726, -11.2110]])


In [69]:
#matmul
mml = torch.matmul(ten, ten2.view(4,3))
print(mml)

tensor([[  0.4038,  -3.1672,  -4.4221],
        [ -1.8757,  -1.8439,  -6.8754],
        [ -8.7291,   3.5726, -11.2110]])


In [70]:
add = ten+ten2
print(add)

tensor([[-0.0556,  4.0221,  3.9385,  2.8324],
        [ 2.9571,  2.4540,  5.5390,  5.8334],
        [ 2.7921,  8.5444,  4.8491,  0.5888]])


In [83]:
summa = torch.sum(ten*ten2)
print(summa)

tensor(-7.0688)
