In [13]:
import torch

In [20]:
ten = torch.tensor([
    [1,2,3,4],
    [3,4,5,6],
    [3,8,6,1]
], dtype=torch.float32)
print(ten)

tensor([[1., 2., 3., 4.],
        [3., 4., 5., 6.],
        [3., 8., 6., 1.]])


In [22]:
ten.size()

torch.Size([3, 4])

In [23]:
ten.shape

torch.Size([3, 4])

In [24]:
len(ten.shape)

2

In [35]:
torch.tensor(ten.shape).prod()

tensor(12)

In [37]:
ten.numel()

12

In [42]:
ten.reshape(2,6)

tensor([[1., 2., 3., 4., 3., 4.],
        [5., 6., 3., 8., 6., 1.]])

In [50]:
print(ten.reshape(1,12).squeeze())
print(ten.reshape(1,12).squeeze().shape)

tensor([1., 2., 3., 4., 3., 4., 5., 6., 3., 8., 6., 1.])
torch.Size([12])


In [55]:
print(ten.reshape(2,6).unsqueeze(dim=0))
print(ten.reshape(2,6).unsqueeze(dim=0).shape)

tensor([[[1., 2., 3., 4., 3., 4.],
         [5., 6., 3., 8., 6., 1.]]])
torch.Size([1, 2, 6])
